name: Install cpanminus
description: Install cpanminus from web

runs:
  using: composite
  steps: 
    - run: curl -L -s -o cpanminus.pl https://cpanmin.us
      shell: bash
    - run: perl cpanminus.pl App::cpanminus local::lib
      shell: bash
    - run: rm -f cpanminus.pl
      shell: bash
    - run: find /home/runner/work/_actions
      shell: bash
    - run: use File::Spec; exec($^X, File::Spec->catfile(File::Spec->catdir(q<${{ github.action_path }}>, q<bin>), q<configure_local_lib.pl>));
      shell: perl -- {0}
